const cardsData = [
  {
    id: 1,
    rname: 'Cake',
    imgdata: require('../images/cake.jpg'),
    recommendedDishes: 'Burger, Pastry',
    somedata: ' 1175 + order placed from here recently',
    price: 550,
    rating: '4.8',
    qnty: 0,
  },
  {
    id: 2,
    rname: 'Burger',
    imgdata: require('../images/burger.jpg'),
    recommendedDishes: 'Cake, Pastry',
    somedata: ' 2525 + order placed from here recently',
    price: 65,
    rating: '3.9',
    qnty: 0,
  },
  {
    id: 3,
    rname: 'Momos',
    imgdata: require('../images/momos.jpg'),
    recommendedDishes: 'Pizza, Pasta',
    somedata: ' 650 + order placed from here recently',
    price: 70,
    rating: '4.2',
    qnty: 0,
  },
  {
    id: 4,
    rname: 'Chai',
    imgdata: require('../images/chai.jpg'),
    recommendedDishes: 'Samosa',
    somedata: ' 300 + order placed from here recently',
    price: 30,
    rating: '3.8',
    qnty: 0,
  },
  {
    id: 5,
    rname: 'Pizza',
    imgdata: require('../images/pizza.jpg'),
    recommendedDishes: 'Pasta, Noodles',
    somedata: '1050 + order placed from here recently',
    price: 330,
    rating: '4.4',
    qnty: 0,
  },
  {
    id: 6,
    rname: 'Samosa',
    imgdata: require('../images/samosa.jpg'),
    recommendedDishes: 'Wraps, Chai',
    somedata: ' 1100 + order placed from here recently',
    price: 20,
    rating: '3.8',
    qnty: 0,
  },
  {
    id: 7,
    rname: 'Pasta',
    imgdata: require('../images/pasta.jpg'),
    recommendedDishes: 'Burger, Pizza',
    somedata: '500 + order placed from here recently',
    price: 170,
    rating: '3.8',
    qnty: 0,
  },
  {
    id: 8,
    rname: 'Veg Roll',
    imgdata: require('../images/roll.jpg'),
    recommendedDishes: 'Momos',
    somedata: '500 + order placed from here recently',
    price: 40,
    rating: '3.2',
    qnty: 0,
  },
  {
    id: 9,
    rname: 'Noodles',
    imgdata: require('../images/noodles.jpg'),
    recommendedDishes: 'Burger',
    somedata: '2525 + order placed from here recently',
    price: 120,
    rating: '3.8',
    qnty: 0,
  },
];

export default cardsData;
